# Generated by Django 4.0.1 on 2022-01-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verb',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='verb',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
